version: '3'
services:
  7_days_to_die:
    container_name: 7_days_to_die
    hostname: 7_days_to_die
    image: 7_days_to_die:latest
    restart: unless-stopped
    ports:
      - 8080-8081:8080-8081/tcp
      - 8082:8082/tcp
      - 26900:26900/tcp
      - 26900-26902:26900-26902/udp
    volumes:
      - Mods:/7daysded/Mods/
      - Data:/7daysded/.local/share/7DaysToDie
      - Logs:/7daysded/logs

volumes:
  Mods:
  Data:
  Logs: